export const appName = process.env.NEXT_PUBLIC_APP_NAME || "NextFire";
export const appTitle = process.env.NEXT_PUBLIC_APP_TITLE || "Next.js + Firebase + Shadcn UI Template";
export const hostname = process.env.NEXT_PUBLIC_HOSTNAME;
export const baseUrl = hostname ? `https://${hostname}` : "";
export const emailLinkLoginUrl = `${baseUrl}/auth/email-link-login`;
export const privacyPolicyUrl = process.env.NEXT_PUBLIC_PRIVACY_POLICY_URL || `${baseUrl}/policies/privacy`;
export const termsOfServiceUrl = process.env.NEXT_PUBLIC_TERMS_OF_SERVICE_URL || `${baseUrl}/policies/terms`;
export const primaryColor = process.env.NEXT_THEME_PRIMARY_COLOR || "#171717";
export const primaryForegroundColor = process.env.NEXT_THEME_PRIMARY_FOREGROUND_COLOR || "#fafafa";
export const legalBusinessName = process.env.NEXT_PUBLIC_LEGAL_BUSINESS_NAME || appName;
export const legalBusinessAddress = process.env.NEXT_PUBLIC_LEGAL_BUSINESS_ADDRESS
export const legalBusinessCountry = process.env.NEXT_PUBLIC_LEGAL_BUSINESS_COUNTRY
export const legalContactEmail = process.env.NEXT_PUBLIC_LEGAL_CONTACT_EMAIL
export const reCaptchaSiteKey = process.env.NEXT_PUBLIC_RE_CAPTCHA_SITE_KEY;
